name: FluOcean Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '#Skip')"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (build project)
        run: ./gradlew build -x test

      - name: Build with Gradle (shadow)
        run: ./gradlew shadowJar

      - name: Build with Gradle (collect)
        run: ./gradlew collect

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs